---
title: "Chicken Noodle Soup"
description: |
  Chicken noodle
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
2tablespoons unsalted butter
1medium yellow onion, finely chopped
Salt and black pepper
8cups chicken stock
2bay leaves or thyme sprigs (or 1 teaspoon dried thyme)
¼cup finely chopped parsley or dill, stems reserved, plus more for garnish
2medium carrots, cut into ½-inch pieces
2celery stalks, cut into ½-inch pieces
6ounces dried noodles, such as egg noodles or short pasta
3cups shredded, cooked chicken (from 1 rotisserie chicken)

# Instructions
## 1
In a large pot or Dutch oven, melt the butter over medium. Add the onion, season with salt and pepper, and cook until softened but not browned, 5 to 7 minutes.

## 2
Add the chicken stock, bay leaves and herb stems and bring to a boil over high. Add the carrots, celery and noodles and cook, uncovered, over medium-high until the pasta is al dente according to package directions, 7 to 10 minutes. Add the chicken and simmer just until warmed, 1 to 2 minutes. Pluck out the bay leaves and herb stems, stir in the chopped parsley, and season to taste with salt and pepper.