---
title: "Shawarma-Spiced Grilled Chicken With Tahini-Yogurt Sauce"
categories: [Chicken, Favourites]
---

# Ingredients
## For the Chicken
- 1 tsp sweet paprika
- 1 tsp ground cumin
- 0.5 tsp ground coriander
- 0.5 tsp ground ginger
- 0.5 tsp ground turmeric
- 0.25 tsp ground allspice
- 0.25 tsp ground cinnamon
- Salt and pepper
- 1.5 cups plain yogurt
- 0.25 cup minced yellow onion
- 3 tbsp extra-virgin olive oil, plus more for the grill
- 2 garlic cloves, minced
- 3 pounds boneless, skinless chicken breasts or thighs (or a combination)
- Half lemon, for serving
- Fresh parsley or mint leaves (optional), for serving

## For the Tahini-yogurt Sauce
- 1 cup plain yogurt
- 2 tbsp tahini
- 1 tbsp freshly squeezed lemon juice
- Garlic clove, finely grated or minced
- Salt

# Instructions
## 1 - Make the marinade
- In a large bowl, combine:
  - paprika
  - cumin
  - coriander
  - ginger
  - turmeric
  - allspice
  - cinnamon
  - 1.5 tsp salt
  - 0.5 tsp pepper
- Add the yogurt, onion, olive oil and garlic
- Mix well, then set aside

## 2
- Pat the chicken pieces dry with a paper towel
- If using breasts, cut the breasts in half crosswise, so you have one thicker, rounded piece and one thinner, triangular piece
- Working in batches, place the chicken pieces on a large cutting board and cover them with a sheet of parchment paper
- Using a meat mallet or rolling pin, pound the chicken until each piece is about the same thickness as the others, between 0.5-inch and 0.75-inch-thick
- Be careful not to pound so hard that you tear the chicken

## 3
- Add the chicken to the marinade and toss well
- Cover and refrigerate for at least 3 hours or up to 24 hours

## 4 - Make tahini yogurt sauce
- In a small bowl, combine the yogurt, tahini, lemon juice and garlic; season to taste with salt
- Refrigerate for at least 30 minutes or up to 3 days

## 5
- Before grilling, let the chicken come to room temperature for 30 minutes
- If using a charcoal or gas grill, clean the grates and brush them with oil
- Set the grill to medium-high or heat a grill pan slicked with olive oil on the stovetop over medium-high

## 6
- Lift the chicken from the marinade (no need to brush off excess marinade) and grill until cooked through, 6 to 8 minutes on each side, covering the grill halfway through, if necessary, to retain the heat

## 7
- Transfer the chicken to a plate, sprinkle generously with salt and squeeze the lemon half over the pieces
- Allow the chicken to rest for at least 10 minutes before serving
- Garnish with chopped fresh parsley or mint (if using) and serve the tahini-yogurt sauce on the side