---
title: "Smoky Sweet Potato and Chickpea Sheet Pan Dinner"
categories: Veggie
---

# Ingredients
- 1, 15oz can chickpeas, rinsed and drained
- 1 medium sweet potato, chopped into small cubes (½ inch thick)
- 1 head of broccoli, chopped into small ping pong sized florets
- 1/2 medium red onion, sliced thin
- 1 tsp smoked paprika
- 1/2 tsp fennel seed
- 1/2 tsp dry thyme
- 1/2 tsp dry basil
- 1/2 tsp ground cumin
- 1 tsp garlic powder
- Salt and Pepper to taste
- 1–2 tbsp olive oil
- Handful of fresh minced parsley and cilantro

# Instructions
## 1
- Set oven to 400F
- Dry off your chickpeas in a clean kitchen towel and lightly rub it over the chickpeas
- Remove any loose chickpea skins that come off

## 2
- Add your chickpeas and sweet potato to a large parchment lined sheet pan and drizzle with half of the olive oil, dry herbs and spices
- With your hands toss everything together evenly and then spread your chickpeas and potatoes out into a single layer

## 3
Place the sheet pan into the oven and bake for 20 minutes

## 4
Carefully remove the sheet pan, give the chickpeas and sweet potato a toss with a spatula and push them a bit to the side to make room for your broccoli and red onion

## 5
To the broccoli and red onions, drizzle with your remaining oil, herbs and spices and toss together with your hands and spread out again on your sheet pan

## 6
Return the pan to the oven for an additional 10-15 minutes, and when done cooking sprinkle with some fresh herbs like cilantro and parsley and serve

# Notes
 - Make sure to dry your chickpeas really well. I like to rub the cloth over the chickpeas to help encourage some of the chickpea skins to come off (you don’t have to remove all the chickpea skins). This results in less moisture for the chickpeas and allows them to roast better
 - Cook your sweet potato and chickpeas first as they need more time to roast compared to the broccoli and onions. This will ensure that your sweet potato cooks all the way through
- Avoid having your main ingredients lay on top of each other on the sheet pan. Make sure to spread everything out in a single layer, preferably giving space between veggies so that they brown nicely
- Pro-tip: If a little dairy is OK with you, some crumbled feta on top of the plated dish really takes everything over the top