---
title: "Braised Pork Chops, Shanghai-style"
categories: Pork
---

# Ingredients
- 2 lb boneless center cut pork chops
(6 pieces)
- 2 tbsp Shaoxing wine
- 1/2 tsp salt
- 1 tbsp light soy sauce
- 3-4 tbsp water
- 2 medium eggs
- 1/3 cup cornstarch

For the rest of the dish:
- 2-3 bunches green onions
- 1/3 cup neutral oil (such as vegetable, canola, or avocado oil)
- 15 g rock sugar (or substitute 1 tbsp granulated sugar for 15g rock sugar)
- 1 1/4-1 1/2 cups water (use less water if your stove has lower BTUs, or more if your stove is very hot)
- 2 tablespoons light soy sauce
- 1 1/2 tablespoons dark soy sauce

# Instructions
## 1
- For each pork chop, cut 2 small slits along the pork fat on the outer perimeter of the chop to prevent it from curling up during the cooking process
- Then pound it front and back using the back of your knife (or a meat tenderizer), until the chops are between ¼ and ½ inch thick (about 0.75cm)
- This is an important step
- Take your time to do it thoroughly

## 2
- Mix the pork chops with the Shaoxing wine, salt, light soy sauce, and water, using your hands to toss the chops until they absorb all the liquid

## 3
- Add 2 medium eggs, and mix until everything is well absorbed and the chops are uniformly coated in egg
- Finally, add the cornstarch and mix everything well one more time
- Marinate for 15 minutes

## 4
- Wash the scallions and pat them thoroughly dry with a kitchen towel to prevent splattering in the wok later
- Cut them in half crosswise
- If the stems are particularly thick, you can also cut them in half lengthwise.

## 5 
- Preheat your wok over medium-high heat until it starts to smoke
- Coat the bottom of the wok with 1/3 cup of oil
- Test the oil temperature by sticking a chopstick in the oil
- A stream of small bubbles means the oil is hot enough to cook the chops
- Add the pork chops in two batches, cooking each side for 30 seconds to 1 minute, until the pork chops are a light golden color and the coating is set
- Avoid over-frying, or the meat will become tough
- Transfer to a plate

## 6
- There should be some oil left in the wok
- If not, add a couple tablespoons
- Over medium heat, add the scallions
- Cook for a few minutes until they are wilted and lightly browned around the edges

## 7
- Place the pork chops on top of the bed of scallions
- Add the rock sugar, water, light soy sauce, and dark soy sauce. With the heat still at medium, cover and simmer for about 3 minutes

## 8
- Remove the lid, flip the pork chops, and submerge them under the sauce
- Cover and simmer for another 2-3 minutes

## 9
- Remove the cover, and increase the heat to high
- Stir everything well one more time, and quickly transfer all of the pork chops to a serving platter

## 10
- Let the sauce thicken, cooking for 1-2 minutes, stirring occasionally with your wok spatula and letting it turn glossy and thick enough to coat the spatula
- You will still want some sauce to mix with your rice, so don’t reduce it too much!

## 11
- Spread the scallions over the pork chops, and pour the sauce over the whole thing
- Serve!