---
title: "Spiced Roasted Cauliflower With Feta and Garlic"
description: |
  Roasted cauliflower
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
1small head cauliflower
6garlic cloves, smashed
3tablespoons olive oil, plus more for serving
2teaspoons fennel or cumin seed
1teaspoon ground turmeric
Pinch of red-pepper flakes
Kosher salt and ground pepper
1ounce feta cheese, sliced or crumbled
¼ cup parsley, tender leaves and stems, coarsely chopped
¼ cup cilantro, mint or dill, tender leaves and stems, coarsely chopped

# Instructions
## 1
Heat oven to 450 degrees. Slice cauliflower lengthwise into ½-inch thick slices, including the core and leaves. (Some of the first slices will crumble and fall apart. This is O.K., and will be useful when you want those crispier bits.)

## 2
Place cauliflower (slices and crumbles) and garlic on a rimmed baking sheet and drizzle with olive oil. Sprinkle with fennel seed, turmeric and red-pepper flakes, and season with salt and pepper.

## 3
Roast, without disturbing, until cauliflower has turned a deep golden brown and crisped up in spots, 25 to 30 minutes. Using a spatula, flip the larger steaks and stir the smaller bits around and continue to roast until completely and evenly browned, another 8 to 10 minutes.

## 4
Remove from heat and transfer to a large serving platter. Top with feta, herbs and a drizzle of olive oil.