---
title: "Roasted Brussels Sprouts Caesar With Tahini"
description: |
  Caesar Sprouts
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
2pounds brussels sprouts, ends trimmed, large ones quartered, smaller ones halved
6tablespoons olive oil
1teaspoon ground cumin
¼teaspoon crushed red pepper
Salt and pepper
3cups of ½-inch bread cubes (from about ½ French baguette or loaf of crusty bread)
1large lemon, juiced (about 3 tablespoons)
2tablespoons tahini
1garlic clove, grated or minced
2tablespoons plus ¼ cup grated Parmesan

# Instructions
## 1
Heat the oven to 425 degrees. On a sheet pan, drizzle the brussels sprouts with 3 tablespoons olive oil; season with the cumin and red pepper, plus salt and pepper. Toss until everything is glistening.

## 2
Roast until the Brussels sprouts start to brown in spots, 12 to 15 minutes.

## 3
In a medium mixing or serving bowl, toss the bread with 1 tablespoon oil and season lightly with salt. Remove the brussels sprouts from the oven, move them around with a wooden spoon, spread out in an even layer and add the bread cubes on top. Cook until the sprouts are tender and browned and the bread toasted, 8 to 12 minutes more.

## 4
Meanwhile, in the same bowl, combine the lemon juice, tahini and garlic with 2 tablespoons grated Parmesan, 2 tablespoons water and the remaining 2 tablespoons of olive oil until smooth. Remove the sheet pan from the oven. Drizzle with the dressing, sprinkle with most of the remaining ¼ cup cheese and toss to combine.

## 5
Transfer to the serving bowl or serve directly from the sheet pan. Garnish with the remaining cheese and a few grinds of pepper.