---
title: "Pasta Salad"
categories: [Salad, Pasta, Favourites]
---

# Ingredients

## For the Dressing
- 4 tbsp red wine vinegar
- 1 garlic clove, minced
- 1 tsp dried oregano
- Salt and freshly ground black pepper
- 1/3 cup EVOO

## For the Pasta
- 500g short-cut pasta, such as farfalle
- 1 pint cherry or grape tomatoes, halved
- 8 oz mozzarella, cubed (or use small mozzarella balls)
- 4 oz salami, sliced, quartered 
- 0.5 cup cucumber, thinly sliced
- 1 cup parsley, coarsely chopped
- 1 cup basil, coarsely chopped

# Instructions
## 1 - Make the dressing
- Combine vinegar, garlic, oregano and a big pinch each salt and pepper in a large bowl
- Whisk in oil; taste and add more salt, pepper or vinegar as needed
- Set aside

## 2 - Prepare the pasta
- Bring a large pot of heavily salted water to a boil
- Cook the pasta according to the package directions until the pasta is al dente
- Drain well, transfer to the large bowl, and toss with the dressing while still warm

## 3
- Add tomatoes, mozzarella, salami, cucumber to the bowl and toss well; fold in herbs
- Taste and season with more salt, pepper and vinegar, if you like

## 4
- Drizzle with olive oil and top with cracked black pepper just before serving