---
title: "5 Weeks - Day 2"
description: |
  We doing this
author: Michael Ellsworth
date: 2024-04-21
---

To be honest, I didn't think I'd get to day 2. This is a pretty big accomplishment. I can now draw a trend line. Two days in a row, baby!

Today I completed the tedious task of creating READMEs for each of my contributions to Tidy Tuesday. This was a good exercise in making my weekly submissions more visible, as well as setting my repository up for extracting plot titles for the webR app I'm working on. It also helped me realize that I have quite a few unfinished Tidy Tuesday plots.

This reminds me that I should probably brainstorm some things I may want to accomplish over these 5 weeks. Considering I made it to day 2 (hell yeah!), there is a much more likely chance that I may actually accomplish a few things here. Here's what I have so far:

-   Clean up and finish half baked Tidy Tuesday submissions
    -   Some you've barely started to code, some you've got a pretty garbage looking plot. Clean these bad boys up, Mike!
    -   While I'm here, might as well keep up the weekly habit of contributing to Tidy Tuesday! Flex those ggplot muscles, brother!
    -   More Tidy Tuesday thoughts... What am I learning about each week? Maybe write more about that.
-   Create a shareable webR app to display Tidy Tuesday submissions
    -   I'm hoping this webR app doesn't dominate this "blog" over the next 5 weeks but it's been a slow go so far. But for a good reason. It's been a great learning exercise. Why rush through it?
-   Develop a Shiny application for viewing basic Ultimate statistics
    -   This will be a relatively easy exercise (famous last words you doof!) but it's been a while since I've created anything in Shiny. Time to get on this band wagon again.
-   Figure out how I can intersect my interest in data and my interest in radio/music
    -   I host a weekly radio program where I select records for 90 minutes. I have over 4,000 songs that I've played over the last 4 years. Why not tell some sort of data story here?
-   Explore Survival Analysis in Tidy Models
    -   I've been thinking about a lot of different work related use cases for Survival Analysis recently. Why not check out how it's done in Tidy Models? I'm sure they make it fairly straight forward to do!
-   Plot GitHub contributions at the end of the 5 weeks
    -   There was a ggplot version of this plot that I came across. Try and re-create this.

Perhaps I can do some more brainstorming later but I think that's a good start. Lots to think about over the next 5 weeks!
