---
title: "Chimichurri Meatballs"
description: |
  Chimichurri Meatballs
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
## For the Chimichurri Sauce
1packed cup parsley leaves and tender stems
½packed cup fresh oregano leaves
3garlic cloves
Salt
½cup extra-virgin olive oil
2tablespoons red wine vinegar
½teaspoon crushed red pepper, plus more as needed

## For the Meatballs
1cup panko bread crumbs
1large egg
Kosher salt (such as Diamond Crystal) or fine sea salt
1pound ground beef (preferably 15 percent fat)
1tablespoon extra-virgin olive oil

# Instructions
## 1
To make the chimichurri, on your cutting board or in a food processor, combine the parsley, oregano, garlic and a big pinch of salt. Chop or pulse until a coarse, juicy paste forms, then transfer to a medium bowl. Add the oil, vinegar, crushed red pepper and 1 tablespoon water; mix well. Season to taste with salt and more crushed red pepper to taste. (Sauce can be refrigerated for up to 3 days.)

## 2
In a large bowl, stir the panko, egg, 1 teaspoon kosher salt (or ½ teaspoon fine sea salt) with ¼ cup water and ¼ cup chimichurri until the panko is wet and softened. Add the beef and use your hands to mix until combined.

## 3
Roll the mixture into 12 meatballs (3 tablespoons/2 ounces each) and chill for 5 to 10 minutes to firm slightly.

## 4
Heat the oil in a large, nonstick skillet over medium. Add the meatballs and cook, turning occasionally, until browned and medium-rare, or to desired doneness, 7 to 10 minutes. Serve with remaining chimichurri spooned over top and alongside.