---
title: "Crispy Tofu and Broccoli With Ginger-Garlic Teriyaki Sauce"
description: |
  Crispy tofu
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
## For the Tofu
2(14-ounce) package extra firm tofu, drained
Neutral oil
¾cup cornstarch
Kosher salt (such Diamond Crystal) and black pepper
1pound broccoli, cut into small 1-inch florets, stems reserved for another use
Chopped cilantro leaves, for topping (optional)
Toasted white sesame seeds, for topping (optional)
Cooked rice, for serving
## For the Teriyaki Sauce
½cup soy sauce or tamari
½cup mirin
⅓cup sake
¼cup granulated sugar
1-inch piece ginger, peeled and grated
1garlic clove, peeled and grated

# Instructions
## 1
Arrange racks in the middle and bottom of the oven, and heat the oven to 425 degrees. You will need 2 sheet pans. Line one with parchment paper.

## 2
Prepare the tofu: Cut each block of tofu crosswise into ½-inch slices and pat them dry with a kitchen towel.

## 3
In a large baking dish or rimmed plate, drizzle 3 to 4 tablespoons of oil. In another large baking dish or rimmed plate, scatter the cornstarch, season it with 1 teaspoon of salt and a few pinches of black pepper, and toss to combine.

## 4
Place each slice of tofu in the oil and coat both sides, then dip the tofu into the cornstarch and lightly coat both sides. Place the coated tofu straight onto the lined sheet pan. Continue until all the tofu has been coated. All of the tofu should fit on one sheet pan.

## 5
Place the tofu onto the middle rack in the oven and bake for 30 to 35 minutes, flipping halfway through cooking, until lightly golden and crisp to the touch.

## 6
On the second sheet pan, lay out the broccoli and drizzle with oil. Season with salt and black pepper. Place on the bottom rack of the oven and roast for 20 to 22 minutes, until tender and golden in parts.

## 7
Meanwhile, make the teriyaki sauce by combining the soy sauce, mirin, sake, sugar, ginger and garlic in a medium saucepan. Bring to a boil (this should take 2 to 3 minutes), stirring to dissolve the sugar. Once it boils, reduce the heat to medium-low and simmer, stirring occasionally, until there is a layer of light brown foam on top, 12 to 15 minutes. Remove from the heat and let cool for 5 to 10 minutes. It will continue to thicken as it cools.

## 8
To serve, top the rice with the tofu and broccoli and drizzle with the teriyaki sauce. If using, finish with cilantro leaves and sesame seeds.
