---
title: "Grilled Shrimp With Chile and Garlic"
description: |
  BBQ shrimp
author: Michael Ellsworth
date: 2025-02-17
---

# Ingredients
6garlic cloves
½ to 1fresh hot chile, such as jalapeño or Fresno (depending on the chile’s kick and your heat tolerance)
¼cup mayonnaise
1½teaspoons kosher salt (such as Diamond Crystal)
Heaping ¼ teaspoon baking soda
1½pounds large shrimp, peeled and deveined, tails on, patted dry

# Instructions
## 1
Prepare a charcoal or gas grill for high heat. (If you don’t have a grill, you can cook the shrimp in a cast-iron skillet over high heat, with the vent on, following the same timing.) Using a Microplane or the small holes of a box grater, grate the garlic and chile into a medium bowl. Stir in the mayonnaise, salt and baking soda. Add the shrimp and stir to combine. Refrigerate for 15 to 30 minutes.

## 2
Clean the grates with a grill brush (no need to grease the grates), then grill the shrimp until well browned, 2 to 4 minutes. (If using a gas grill, close the lid to maintain temperature.) Flip and cook until opaque throughout, 1 to 2 minutes. Eat right away.