---
title: "Crisp Gnocchi With Brussels Sprouts and Brown Butter"
description: |
  Crisp Gnocchi
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
1pound brussels sprouts (or cruciferous vegetables like broccoli, cauliflower or even cabbage)
1lemon
4tablespoons extra-virgin olive oil
Kosher salt (such as Diamond Crystal) and black pepper
½teaspoon red-pepper flakes
1(18-ounce) package shelf-stable or refrigerated potato gnocchi
6tablespoons unsalted butter, sliced into 6 pieces
½teaspoon honey
Freshly grated Parmesan, for serving

# Instructions
## 1
Trim and halve the brussels sprouts. Using a vegetable peeler, peel thick strips of lemon zest, then coarsely chop. (You should have about 2 teaspoons chopped zest.)

## 2
In a large (preferably 12-inch) skillet, heat 3 tablespoons olive oil over medium-high. Add the brussels sprouts, season with ½ teaspoon salt and a few grinds of pepper, then arrange the brussels sprouts in an even layer, cut side down. Scatter the lemon zest over the top and cook, undisturbed, until the brussels sprouts are well browned underneath, 3 to 5 minutes. Add the red-pepper flakes, stir and cook until the brussels sprouts are crisp-tender, 2 to 3 minutes. Transfer to a medium bowl.

## 3
In the same skillet, heat the remaining 1 tablespoon olive oil over medium-high. Break up any gnocchi that are stuck together, add them to the pan and cook, covered and undisturbed, until golden brown on one side, 2 to 4 minutes. Add the butter and honey, season with salt and a generous amount of black pepper, and cook, stirring, until the butter is golden, nutty smelling and foaming, 1 to 2 minutes. Stir in the brussels sprouts until warmed through. Serve with grated Parmesan.
