---
title: "Blackened Chicken Breasts"
description: |
  Blackened Chicken Breasts
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
1tablespoon kosher salt, such as Diamond Crystal (or 1¾ teaspoons coarse kosher salt)
1tablespoon smoked paprika
½tablespoon dried thyme
½tablespoon dried oregano
½tablespoon garlic powder
½tablespoon onion powder
1teaspoon mustard powder
1teaspoon ground cayenne
2boneless, skinless chicken breasts, about 1½ to 2 pounds (see Tip)
2tablespoons vegetable oil

# Instructions
## 1
Make the blackening seasoning: In a small bowl, combine the salt, smoked paprika, thyme, oregano, garlic powder, onion powder, mustard powder and cayenne.

## 2
Carefully slice the chicken breasts horizontally in half, then pat dry with a paper towel. Thoroughly coat all sides with the blackening seasoning and set aside.

## 3
Drizzle oil into a large skillet or cast iron pan over medium-high. When the oil begins to shimmer, carefully place the chicken in the pan and cook undisturbed for 5 minutes. Watch out for any oil splattering and popping out of the pan. Cook until the seasoning literally darkens. After 5 minutes, flip the chicken and cook for another 3 minutes.

## 4
Turn off the heat and leave the pan tented with aluminum foil for 5 minutes (this will help the chicken continue cooking from the residual heat without drying out). Remove the foil, then let the chicken rest for at least 2 minutes.

## 5
When ready to serve, slice the chicken on a bias into ½-inch pieces. Serve immediately.

## Tip
About 30 minutes before prepping, remove the chicken from the refrigerator to allow it to come to room temperature.
