---
title: "Soy Sauce Noodles With Cabbage and Fried Eggs"
description: |
  Soy Sauce Noodles
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
## For the Noodles
Kosher salt
7ounces dried (or 16 ounces fresh) thin egg noodles
Neutral oil, such as vegetable or grapeseed
4large eggs
½small green cabbage (1½ pounds), core removed then thinly sliced
1bunch scallions (about 8 stems), white and green parts separated and cut into 2-inch segments
White pepper
Toasted white sesame seeds, optional

## For the Soy Sauce Seasoning
2tablespoons soy sauce
2tablespoons dark soy sauce (or tamari)
1tablespoon toasted sesame oil

# Instructions
## 1
Prepare the noodles: Bring a large pot of salted water to a boil. Add the noodles and stir to loosen them up. Cook, according to package instructions until just tender, then rinse under running water until cold. Drain and set aside.

## 2
Make the seasoning: Mix together the soy sauce, dark soy sauce and sesame oil along with 3 tablespoons of water. Set aside.

## 3
Finish the noodles: Heat a wok or large well-seasoned cast iron or nonstick skillet over medium high. When hot, add a drizzle of oil and crack in the eggs, adding however many will comfortably fit in your pan; you may need to work in batches. Reduce the heat to medium and fry until the edges are frizzled, the whites are set and the yolk is cooked to your liking. Season with a pinch of salt. Remove and repeat with the remaining eggs. Set aside.

## 4
To the same pan, add 2 tablespoons of oil. Add the cabbage and season with ½ teaspoon of salt. Toss the cabbage until it has softened and reduced significantly in size, 2 to 3 minutes. Add the white part of the scallions and toss for 2 minutes until they have softened. Add the noodles and soy sauce seasoning, and toss for 2 minutes until well coated. Add the green parts of scallions and toss for 1 to 2 minutes until wilted. Turn off the heat and add ½ teaspoon of white pepper.

## 5
To serve, place noodles in serving bowls and top with toasted sesame seeds, if using, and a fried egg.