---
title: "Timezone transitions"
description: |
  Tidy Tuesday 2023 Week 13
date: 2024-04-28
---

I spent the whole day playing around with my plot for Tidy Tuesday week 2023-03-28, the timezone transitions week. In addition to struggling to figure out what to plot with this data, I spent probably an hour trying to figure out how to include a hyperlink in a ggplot2 image. A lot more difficult than I expected! I never did find a simple enough solution for my liking so I have now moved on. This [stack overflow](https://stackoverflow.com/questions/42259826/hyperlinking-text-in-a-ggplot2-visualization) post appeared to have the most promise but the juice just wasn't worth the squeeze for my use case. I feel like coming back to this issue but perhaps at a later date. And perhaps next Sunday I'll get around to cleaning this blog.

Looking back at the 2023-03-28 Tidy Tuesday README, there is a link to Twitter's guidelines for how to add alt text to your images. To my surprise, the link isn't broken! Looks like the folks who maintain the Tidy Tuesday repository gave up on mentioning Twitter on 2023-07-25 though.

2023-03-28 is all about timezones. The plot ideas aren't coming to me quickly here but I did manage to uncover some interesting tidbits about my timezone (Canada/Mountain).

-   The official record of the Canada/Mountain timezone began in 1906-09-01
-   Initially, the timezone did not include daylight savings time until 1918
-   DST was then abandoned between 1923 and 1942 before changing to permanent DST between 1942 and 1945
-   After some brief back and forth between DST and standard time, permanent standard time lasted from 1947 to 1972. The glory years.
-   From 1972 on, the twice a year switch between DST to ST persists. Boo!