---
title: "Silken Tofu With Spicy Soy Dressing"
description: |
  Silken tofu
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
## For the Spicy Soy Dressing
¼cup soy sauce
1tablespoon rice vinegar
1tablespoon sesame oil
1tablespoon chile oil
1tablespoon toasted white sesame seeds
2teaspoons granulated sugar
1scallion, green and white parts, finely sliced

## For the Tofu
2(14-ounce) blocks silken tofu, cold
1scallion, green and white parts, thinly sliced
Handful of cilantro leaves

# Instructions
## 1
Make the dressing: Combine the soy sauce, rice vinegar, sesame oil, chile oil, sesame seeds, sugar and scallion in a small bowl. Whisk until the sugar has dissolved.

## 2
Carefully drain the liquid from the package of tofu, and gently tip the block onto a kitchen towel. (Try to keep the block in one piece, if possible, but don’t worry if it falls apart; it will still taste great.) Pat with another clean kitchen towel, removing as much liquid as possible. Transfer the blocks to one large plate or two smaller plates — leave whole or cut into 1-inch blocks — and spoon the soy dressing over the top until the tofu is completely covered. Top with scallions and cilantro leaves, and eat on its own or with rice or noodles on the side.