---
title: "Cauliflower Shawarma With Spicy Tahini"
author:
  - name: "New York Times"
    href: https://cooking.nytimes.com/recipes/1023019-cauliflower-shawarma-with-spicy-tahini
categories: [Veggie, Favourites]
---

# Ingredients
## For the Cauliflower
- 5 tbsps extra-virgin olive oil
- 1 1/4 tsps ground cumin
- 1 1/4 tsps sweet paprika
- 3/4 tsp fine sea or table salt
- 1 tsp ground coriander
- 1/4 tsp ground turmeric
- 1/4 tsp freshly ground black pepper
- Pinch of ground cayenne
- 1 large head cauliflower (1kg)
- 1 large red onion,

## For the Spicy Tahini Sauce
- 1 tbsp lemon juice
- 1 to 2 tsps harissa paste
- 1 garlic clove
- 1/4 tsp salt
- 1/3 cup tahini
- 1/3 cup ice water

## For serving
- Pita or flatbread
- 1/4 cup parsley
- Chopped tomato and cucumber, for serving

# Instructions
## 0.5 Prepare ingredients
- Trim cauliflower and cut into bite-size florets
- Cut red onion into quarter-inch wedges
- Coarsely chop parsley
- Mince garlic

## 1 Prepare oven
- Arrange racks in the upper and lower thirds of your oven
- Heat oven to 425 degrees

## 2 Prepare the cauliflower
- In a large bowl, whisk together:
  - olive oil
  - cumin
  - paprika
  - salt
  - coriander
  - turmeric
  - black pepper
  - cayenne
- Add cauliflower and onion, toss until well coated
- Spread mixture on a baking sheet into a single layer 

## 3 Roast vegetables
- Roast vegetables for 30 to 40 minutes
  - Top oven rack until golden brown, slightly crisp and tender
  - Stir once or twice during roasting

NOTE: If the vegetables look dry as they roast, drizzle with a little more olive oil

## 4 Prepare the tahini sauce
- Whisk together in a small bowl and let sit for a minute or two to mellow the garlic:
  - lemon juice
  - 1 tsp harissa
  - garlic
  - salt
- Whisk in tahini
- Whisk in ice water, 1 tbsp at a time, until the sauce is smooth and thin enough to drizzle
  - You may not need all of the water or you may need to add a little more. Tahini brands vary a lot.
- Taste and adjust seasoning, adding more harissa, lemon juice and salt if you like
  - The sauce should taste zippy and creamy

## 5 Prepare the pitas
- Warm the pitas or flatbread by placing them directly on the bottom oven rack (or on another baking pan) during the last 5 minutes as the vegetables roast

## 6 Serve
- Scatter parsley on top of the roasted vegetables and serve with warm pitas, tahini sauce, chopped tomato, and cucumber