---
title: "Sheet Pan Chicken Fajitas"
author:
  - name: "Sheet Pan Everything"
    url: https://boutique.ricardocuisine.com/en/sheet-pan-everything-book.html
categories: Chicken
---

# Notes
- Recipe is a bit oily - could cut back on vegetable oil

# Ingredients
## Chicken
- 1 red onion
- 2 bell peppers (various colours)
- 675g chicken thighs (boneless) or chicken breasts
- 1 tbsp chili powder

## Suggested toppings
- 8 medium soft tortillas
- 1 lime
- Cilantro
- Cheddar cheese
- Salsa, guac, sour cream

# Instructions
## 0.5 - Prepare ingredients
- Cut red onion into very thin wedges
- Seed and cut bell peppers into strips
- Cut chicken into strips (if using chicken breast, cut in half horizontally before cutting into strips)

## 1 - Chicken
- Preheat oven to 425F (rack in the middle)
- Combine onion and bell peppers with 1 tbsp of oil on a non-stick sheet pan
- Combine chicken, chili powder and 1 tbsp of oil in a bowl
- Add chicken to sheet pan with vegetables
- Bake for 20 minutes

## 2 - Toppings
- Wrap tortillas in foil, place on oven rack for last 5 minutes of chicken cooking time