---
title: "Crispy Fried Rice With Bacon and Cabbage"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/1020887-crispy-fried-rice-with-bacon-and-cabbage
categories: Rice
---

# Ingredients
- 5 tbsp neutral oil
- 3 slices thick-cut bacon, in 0.5-inch pieces (about 3 ounces)
- 1 small bunch scallions, whites and greens separated, sliced
- 4 cups shredded cabbage (from about half small head)
- Salt
- 4 garlic cloves, minced
- 6 cups cooked rice, white or brown, preferably day-old
- 2.5 tbsp fish sauce
- 0.5 tbsp soy sauce
- 0.5 cup kimchi, drained and chopped, plus more for serving if you like
- 0.5 cup green peas (thawed, if frozen)
- 4 fried eggs, for serving (optional)
- Toasted sesame oil, for drizzling (optional)

# Instructions
## 1
- In a large nonstick skillet or wok over medium-high, heat 2 tbsp oil until almost smoking
- Stir in bacon, and cook, stirring constantly, until bacon is golden, about 2 minutes
- Transfer to a heatproof bowl, leaving as much oil in the skillet as you can

## 2
- Add scallion whites to the pan
- Cook until soft, stirring frequently, 1 to 2 minutes
- If the pan looks dry, drizzle in a little more oil, then stir in cabbage and a pinch of salt
- Cook, continuing to stir frequently, until cabbage is soft, 2 to 4 minutes
- Stir in garlic, and cook until fragrant, another 1 to 2 minutes
- Transfer to the bowl with the bacon

## 3
- Add remaining 3 tbsps oil to skillet and raise heat to high
- Add rice, and a large pinch of salt, then toss thoroughly to coat with oil
- Spread out rice in an even layer along the bottom (and sides if in a wok), and drizzle fish sauce and soy sauce over
- Let rice sit until sizzling stops and it starts to crackle and crisp, 1 to 4 minutes
- Toss, taste, and add more fish sauce or soy sauce if necessary

## 4
- Fold in bacon mixture, kimchi and peas, then transfer to plates
- Top with scallion greens, more kimchi to taste, and fried eggs, if using
- Drizzle everything with sesame oil and soy sauce, if you like, and serve immediately
