---
title: "Gyoza"
author:
  - name: "Recipe Tin Eats"
    url: https://www.recipetineats.com/gyoza-japanese-dumplings-potstickers/#recipe
categories: [Pork, Favourites]
---
# Notes
- Replacing chives with green onions (green part) is an option that I think works
- Fattier pork = better!

# Ingredients
## Filling

- Green cabbage
- 1 tsp salt
- 500 g ground pork
- 1 cup garlic chives
- 1 garlic cloves, crushed
- 1 tsp ginger, grated
- 1 tsp sesame oil
- 1 tbsp cornstarch / corn flour
- 2 tsp soy sauce

## Gyoza

- 1 tsp cornstarch (for tray)
- 40 – 45 round (or square) gyoza wrappers
- 3 tbsp vegetable oil

## Dipping sauce
- Soy sauce
- Rice wine vinegar
- Chili oil

# Instructions
## 1 Prepare the cabbage
- Use mandolin to finely slice cabbage, 1.5 cups worth (roughly a quarter of a cabbage)
- Combine cabbage and 1/2 tsp salt in a small bowl
- Set aside for 20 minutes to allow the cabbage to wilt slightly

## 2 Prepare the filling
- Place remaining filling ingredients in a large bowl
  - 1/2 tsp salt
  - 500 g ground pork
  - 1 cup garlic chives
  - 1 garlic cloves, crushed
  - 1 tsp ginger, grated
  - 1 tsp sesame oil
  - 1 tbsp cornstarch / corn flour
  - 2 tsp soy sauce
- Squeeze out any excess water from the cabbage and add to the bowl
- Use your hands to mix the filling

## 3 Wrap the gyoza
- Sprinkle a baking tray with 1 tsp of cornstarch
- Place 1 gyoza wrapper on your palm
- Dip your finger in water and run it around the edge of half the gyoza wrapper (to seal)
- Place 1 slightly heaped tbsp of filling on the wrapper
- Fold wrapper over, create 4 pleats
- Press to seal and place on the tray
- Repeat with remaining wrappers

NOTE: She's got a good video on the site that goes over wrapping instructions in more detail

## 4 Cook the gyoza
- Heat 1 tbsp oil in a large skillet (that has a lid) over medium high heat
- Place about 12 gyoza in rows, slightly overlapping each other on the folded edge
- Cook until the underside is light golden
- Pour 1/3 cup of water around the gyoza and cover with lid
- Cook until the water has completely evaporated and the wrapper is slightly translucent on top (3 to 4 minutes)
- Transfer onto a plate upside down (golden side up)
- Serve with dipping sauce
  - Half soy sauce, half rice vinegar is a good mix