---
title: "Hoison Pork Tenderloin"
author:
  - name: "Sheet Pan Everything"
    url: https://boutique.ricardocuisine.com/en/sheet-pan-everything-book.html
categories: Pork
---

# Ingredients
## Pork
- 1/3 cup hoison sauce
- 1/4 cup vegetable oil
- 3 tbsp soy sauce
- 1 tsp sriracha
- 2 garlic cloves
- 2 pork tenderloins (340g each)

## Vegetables
- 2 sweet potatoes
- 340 g green beans
- 2 tbsp vegetable oil

# Instructions
## 0.5 - Prepare ingredients
- Mince garlic for marinade
- Peel and cut sweet potatoes into wedges
- Trim green beans

## 1 - Marinate pork
- Combine marinade ingredients in a bowl (hoison, oil, soy sauce, sriracha, garlic)
- Salt pork in a marinade container
- Pour marinade onto pork and let marinate for 8 hours or overnight in the fridge

## 2 - Prep vegetables
- Preheat oven to 425F
- Combine sweet potatoes and beans in a large bowl with the 2 tbsp of vegetable oil
- Season vegetables with salt and pepper
- Spread vegetables on non-stick sheet pan
- Bake for 10 minutes

## 3 - Cook pork
- Flip vegetables and move away from center of the sheet pan
- Place pork in the center and drizzle with marinade
- Bake for 15 minutes or until a thermometer in the center of the prok reads 135F
- Remove from heat and cover with foil for 5 minutes

## 4 - Serve
- Slice pork
- Return to sheet pan with vegetables and serve