---
title: "Lamb Kofta Meatballs"
author:
  - name: "RecipeTin Eats"
    url: https://www.recipetineats.com/tray-bake-dinner-lamb-kofta-meatballs/#recipe
categories: [Lamb]
---

# Ingredients
## Koftas
- 1/2 yellow onion
- 500 g ground lamb, or beef
- 1/4 cup panko breadcrumbs
- 2 cloves garlic , finely minced
- 2 tbsp coriander/cilantro, finely chopped
- Olive oil spray

## Kofta Spices
- 2 tsp cumin
- 2 tsp coriander
- 2 tsp paprika (plain, sub smoked)
- 1 1/2 tsp ground cinnamon
- 3/4 tsp cayenne pepper (a bit spicy, reduce to taste or leave out)
- 3/4 tsp cooking salt / kosher salt
- 1/2 black pepper

## Vegetables
- 1 large red bell pepper
- 1 large yellow bell pepper
- 1 red onion
- 1 tbsp extra virgin olive oil
- 1/4 tsp each cooking/kosher salt and pepper

## Serving (optional)
- 4 flatbreads or rice/couscous
- 1 quantity Tahini sauce or lemon yogurt sauce (or even just plain yogurt)
- 3 cups shredded iceberg lettuce (or other leafy greens)
- 2 tomatoes, halved, cut into thin slices
- 1 tbsp cilantro leaves, finely chopped (for sprinkling)

# Instructions
## 0.5
- Preheat oven to 400°F

## 1 - Prep ingredients
- Grate onion for koftas
- De-seed bell peppers and slice into 1 cm thick slices
- Cut red onion into thin wedges for vegetables

## 2 - Prepare meatballs
– Place the Kofta ingredients and spices in a bowl
- Use your hands to combine thoroughly then roll 16 large-ish meatballs (I scoop all mixture onto a tray, then roll into balls)
- Spread them out on a large tray

## 3 - Prepare vegetables
- Toss the vegetables with the oil, salt and pepper
- Scatter around the meatballs.

## 4 - Bake
– Spray the meatballs with oil
- Bake for 15 minutes then switch the oven to the grill/broiler on high
- Cook for a further 5 minutes to get some colour on the surface

##5 - Serve
– Sprinkle with the chopped coriander then serve
- To make wraps, stuff with lettuce, tomato, meatballs, and the cook capsicum and onion
- Drizzle with lots of tahini sauce
- Other ideas: rice or couscous bowls or big salads