---
title: "One-Skillet Orzo With Tomatoes and Eggs"
author:
  - name: "Epicurious"
    href: https://www.epicurious.com/recipes/food/views/easy-one-skillet-orzo-with-tomatoes-and-eggs
categories: Pasta
---

# Ingredients
- 2 tbsp unsalted butter
- 1 small  onion
- 2 garlic cloves
- 1/2 tsp crushed red pepper flakes
- 1 cup orzo
- 828 ml canned whole peeled tomatoes
- 1 1/4 tsp kosher salt
- 4 large eggs
- 100 g (1 cup) mozzarella
- Freshly ground black pepper
- Basil (for serving)

# Instructions
## 0.5 Prepare ingredients
- Finely chop onion
- Thinly slice garlic cloves
- Cut up canned tomatoes in the juice
- Grate mozzarella
- Tear up basil

## 1
- Melt butter in a large skillet over medium heat
- Cook onion, garlic, and red pepper flakes, stirring often, until onion is softened and translucent, about 4 minutes
- Add orzo and stir until coated in butter, about 30 seconds
- Add 2 cups of the cut up tomatoes and juices and cook, stirring, until liquid is reduced and tomatoes are starting to stick to skillet, about 4 minutes.

## 2
- Add salt and 2 cups water, increase heat to medium-high, and bring to a simmer
- Reduce heat to low, cover pan (a baking sheet works well if you don’t have a lid), and cook 8 minutes, stirring halfway through
- Uncover and simmer 1 minute—mixture should be fluid but not watery
- Stir again, then remove from heat and crack each egg into a quadrant of pan

## 3
- Cover pan, set over low heat, and cook, rotating pan every 2 minutes or so, until eggs are nearly set, about 5 minutes
- Sprinkle cheese over, avoiding eggs, cover pan, and cook until cheese is melted, about 2 minutes
- Remove from heat and top with a few grinds of pepper and basil to serve
