---
title: "Shrimp Scampi With Orzo"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/1020330-shrimp-scampi-with-orzo
categories: Fish
---

# Ingredients
- 1 lb large shrimp, peeled and deveined
- 3 tbsp extra-virgin olive oil
- 1 tbsp lemon zest 
- 1 tbsp lemon juice
- 0.5 tsp red-pepper flakes
- Salt
- Pepper
- 4 garlic cloves
- 2 tbsp unsalted butter
- 1 cup orzo
- 1/3 cup dry white wine
- 2 cups boiling water, seafood stock or chicken stock
- 3tbsp finely chopped parsley

# Instructions
## 1
- In a medium bowl, stir together shrimp, 1 tbsp olive oil, lemon zest, red-pepper flakes, 0.5 tsp salt, 0.75 tsp pepper and half of the garlic
- Set aside to marinate (1 hour)

## 2
- Add butter, remaining olive oil and remaining garlic to a medium skillet set over medium heat
- When the butter starts to bubble, add the orzo and 0.5 tsp salt and cook, stirring often, until the orzo is toasted, about 2 minutes, adjusting the heat as necessary to prevent the garlic from burning
- Carefully add the wine — it will bubble — and stir until absorbed, about 1 minute
- Stir in water, reduce heat to low, cover, and cook until orzo is al dente, about 12 minutes

## 3
- Add the shrimp in a snug, even layer on top of the orzo, cover, and cook until all the shrimp is pink and cooked through, 2 to 4 minutes
- Remove from heat and let sit, covered, 2 minutes

## 4
- Sprinkle with parsley and lemon juice, season with salt and pepper, and serve immediately