---
title: "Soy Sauce Noodles With Cabbage and Fried Eggs"
author:
  - name: "New York Times"
    href: https://cooking.nytimes.com/recipes/1023889-soy-sauce-noodles-with-cabbage-and-fried-eggs
categories: Noodles
---

# Ingredients
## For the Noodles
- Kosher salt
- 7 oz dried (or 16 oz fresh) thin egg noodles
- Neutral oil
- 4 large eggs
- ½ small green cabbage (1½ pounds), core removed then thinly sliced
- 1 bunch scallions (about 8 stems), white and green parts separated and cut into 2-inch segments
- White pepper
- Toasted white sesame seeds, optional

## For the Soy Sauce Seasoning
- 2 tbsp soy sauce
- 2 tbsp dark soy sauce
- 1 tbsp toasted sesame oil

# Instructions
## 1 - Prepare the noodles
- Bring a large pot of salted water to a boil
- Add the noodles and stir to loosen them up
- Cook, according to package instructions until just tender, then rinse under running water until cold
- Drain and set aside

## 2 - Make the seasoning
- Mix together the soy sauce, dark soy sauce and sesame oil along with 3 tbsp of water
- Set aside

## 3 - Finish noodles
- Heat a wok or large well-seasoned cast iron or nonstick skillet over medium high
- When hot, add a drizzle of oil and crack in the eggs, adding however many will comfortably fit in your pan; you may need to work in batches
- Reduce the heat to medium and fry until the edges are frizzled, the whites are set and the yolk is cooked to your liking
- Season with a pinch of salt
- Remove and repeat with the remaining eggs
- Set aside

## 4
- To the same pan, add 2 tbsp of oil
- Add the cabbage and season with 0.5 teaspoon of salt
- Toss the cabbage until it has softened and reduced significantly in size, 2 to 3 minutes
- Add the white part of the scallions and toss for 2 minutes until they have softened
- Add the noodles and soy sauce seasoning, and toss for 2 minutes until well coated
- Add the green parts of scallions and toss for 1 to 2 minutes until wilted
- Turn off the heat and add 0.5 teaspoon of white pepper

## 5 - Serve
- Place noodles in serving bowls and top with toasted sesame seeds, if using, and a fried egg