---
title: "Spaghetti Carbonara"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/12965-spaghetti-carbonara
categories: [Pasta, Favourites]
---

# Ingredients
- Salt
- 3 large eggs, room temp
- 50g parmesan
- Coarsely ground black pepper
- 1 tbsp olive oil
- 100g bacon, 1/3 inch sliced squares
- 340g spaghetti

# Instructions
## 1
- Place a large pot of lightly salted water over high heat, and bring to a boil
- Fill a large bowl with hot water for serving, and set aside

## 2
- In a mixing bowl, whisk together the eggs and Parmesan
- Season with a pinch of salt and generous black pepper

## 3
- Set the water to boil
- Meanwhile, heat oil in a large skillet over medium heat, add the pork, and sauté until the fat just renders, on the edge of crispness but not hard
- Remove from heat and set aside.

## 4
- Add pasta to the water and boil until a bit firmer than al dente
- Just before pasta is ready, reheat bacon in skillet, if needed
- Reserve 1 cup of pasta water, then drain pasta and add to the skillet over low heat
- Stir for a minute or so

## 5
- Empty serving bowl of hot water
- Dry it and add hot pasta mixture
- Stir in cheese mixture, adding some reserved pasta water if needed for creaminess
- Serve immediately, dressing it with a bit of additional grated parm and pepper