---
title: "Spiced Roasted Cauliflower With Feta and Garlic"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/1019706-spiced-roasted-cauliflower-with-feta-and-garlic
categories: Veggie
---

# Ingredients
- 1 small head cauliflower
- 6 garlic cloves
- 3 tbsp olive oil
- 2 tsp fennel or cumin seed
- 1 tsp ground turmeric
- Red-pepper flakes
- Kosher salt and ground pepper
- 28 g feta cheese, sliced or crumbled
- 1/4 cup parsley
- 1/4 cup cilantro, mint or dill

# Instructions
## 0.5 Prepare ingredients
- Mince garlic
- Coarsely chop herbs; leaves and stems

## 1
- Heat oven to 450 degrees
- Slice cauliflower lengthwise into half-inch thick slices, including the core and leaves
- Some of the first slices will crumble and fall apart - this is fine and will be useful when you want those crispier bits

## 2
- Place cauliflower (slices and crumbles) and garlic on a rimmed baking sheet and drizzle with olive oil
- Sprinkle with fennel seed, turmeric and red-pepper flakes, and season with salt and pepper

## 3
- Roast, without disturbing, until cauliflower has turned a deep golden brown and crisped up in spots, 25 to 30 minutes
- Using a spatula, flip the larger steaks and stir the smaller bits around and continue to roast until completely and evenly browned, another 8 to 10 minutes

## 4
- Remove from heat and transfer to a large serving platter
- Top with feta, herbs and a drizzle of olive oil