---
title: "Sticky Miso Salmon Bowl"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/1025510-sticky-miso-salmon-bowl
categories: Seafood
---

# Ingredients
- 2 cups rice
- 3 tbsp white miso
- 2 tbsp honey
- 1 tbsp vegetable oil
- 1 tbsp freshly grated ginger
- 2 teaspoons fresh grapefruit zest plus 1 tbsp juice
- 4 x 170g - 230g (800g total) skinless salmon fillets
- 4 green onions
- Optional toppings: kimchi, chile crisp, toasted nori sheets, and sliced cucumber, avocado or radish

# Instructions
## 1 - Cook rice
- Cook rice

## 2 - Prepare ingredients
- Pat salmon dry
- Thinly slice green onions

## 2 - Prepare salmon
- While the rice is cooking, place a rack about 5 inches from the broiler heat source and set the broiler to high
- Whisk the miso, honey, oil, ginger and grapefruit zest and juice in a large bowl
- Season the salmon lightly with salt and add to the bowl
- Gently toss to coat
- Marinate at room temperature, about 10 minutes

## 3 - Cook salmon
- Using tongs, arrange the salmon on a foil-lined rimmed sheet tray
- Make sure to leave the marinade on and spread any excess on top of the fillets. (This step will make for better browning
- Broil the salmon until glossy and charred in most spots, about 5 minutes for medium-rare or 7 minutes for medium

## 4 - Serve
- Uncover the rice and add the scallions
- Serve the salmon over the rice and add any of the toppings you desire
