---
title: "Tzatziki Chickpea Salad"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/1025698-tzatziki-chickpea-salad
categories: [Salad, Veggie]
---

# Ingredients
- 1 cup Greek yogurt
- 1 garlic clove
- 2 tbsp olive oil
- 2 tsp honey
- 1 lemon, halved
- Salt and pepper
- 1 pound mini-cucumbers
- 2 cans (443 ml) chickpeas
- Dill, big handful
- Mint, big handful
- 2 green onions

# Instructions
## 1 - Prep ingredients
- Grate garlic
- Halve cucumbers, lengthwise and cut in 1/2 inch pieces
- Drain chickpeas
- Chop dill and mint
- Thinly slice green onion

## 2 - Prepare dressing
- To a large bowl, add the yogurt, garlic, olive oil, honey and the juice of half a lemon
- Whisk to combine
- If it seems too thick, loosen it up with a splash of water or more lemon juice
- Season well with salt and pepper

## 3 - Combine salad
- To the yogurt, add the cucumbers, chickpeas, dill, mint and scallions, and squeeze the remaining half lemon over the mixture
- Toss to coat
- Taste and season well with salt and pepper

## 4 - Serve
- To serve, drizzle with additional olive oil.