---
title: "Lemony White Bean Soup With Turkey and Greens"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/1021776-lemony-white-bean-soup-with-turkey-and-greens
categories: [Turkey, Soup]
---

# Ingredients
- 3 tbsp olive oil
- 1 onion
- 1 large carrot
- 1 bunch sturdy greens (kale, broccoli rabe, mustard greens or collard greens)
- 1 tbsp tomato paste
- 3/4 tsp ground cumin
- 1/8 tsp red-pepper flakes
- 250 g ground turkey
- 3 garlic cloves
- 1 tbsp finely grated ginger
- 1 tsp kosher salt
- 1 L chicken stock
- 2 cans (400 ml) white beans
- 1 cup chopped fresh, soft herbs (parsley, mint, dill, basil, tarragon, chives or a combination)
- Fresh lemon juice

# Instructions
## 0.5 Prepare ingredients
- Dice onion
- Dice carrot
- Mince garlic
- Drain and rinse beans
- Rinse greens, pull leaves off stems, tear into bite-size pieces

# 1
- Heat a large pot over medium-high for a minute or so to warm it up
- Add the oil and heat until it thins out, about 30 seconds
- Add onion and carrot, and sauté until very soft and brown at the edges, 7 to 10 minutes

# 2
- When the onion is golden, add tomato paste, 3/4 tsp cumin and 1/8 tsp red-pepper flakes to the pot, sauté until paste darkens, about 1 minute
- Add turkey, garlic, ginger and 1 teaspoon salt, and sauté, breaking up the meat with your spoon, until turkey is browned in spots, 4 to 7 minutes

# 3
- Add stock and beans, and bring to a simmer
- Let simmer until the soup is thick and flavorful, adding more salt if needed, 15 to 25 minutes

NOTE: If you like a thicker broth, you can smash some of the beans with the back of the spoon to release their starch. Or leave the beans whole for a brothier soup.

# 4
- Add the greens to the pot and simmer until they are very soft
- This will take 5 to 10 minutes for most greens, but tough greens might take 15 minutes
- Add a little water if the broth gets too reduced

# 5
- Stir herbs and lemon juice into the pot
- Taste and add more salt, cumin and lemon until the broth is lively and bright-tasting
- Serve topped with a drizzle of olive oil and more red-pepper flakes, if desired
