---
title: "Creamy Tortellini Soup"
description: |
  Creamy Tortellini
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
1tablespoon olive oil
1pound loose sweet Italian sausage or sausage links, casings removed (optional )
1medium white or yellow onion, diced
6garlic cloves, minced
1teaspoon paprika
½teaspoon dried fennel seeds
Salt and black pepper
Crushed red pepper
2tablespoons tomato paste
1(28-ounce) can tomato purée
8cups (64 ounces) vegetable or chicken stock
1(9- to 10-ounce) package refrigerated or frozen cheese tortellini
1¼cups heavy cream
1bunch Tuscan (lacinato) kale, leaves stripped and chopped
½cup roughly chopped fresh basil
1lemon, juiced
Grated Parmesan, for serving

# Instructions
## 1
If using the sausage, heat the olive oil in a large pot or Dutch oven over medium-high (if not using sausage, heat the oil on medium, then proceed to step 2.) Add the sausage and cook, breaking it up with a spoon as you go, until it is browned, 5 to 9 minutes. Push the sausage to one side of the pot and spoon out any excess grease, leaving about 2 tablespoons behind.

## 2
If necessary, adjust heat to medium, then add onion, garlic, paprika, fennel, 1½ teaspoons each salt and black pepper, and a pinch of crushed red pepper, and cook, stirring, for 2 minutes, until the onion is just softened and everything is fragrant. Add the tomato paste and cook, stirring, until it darkens, 2 to 3 minutes. Adjust heat to high, stir in tomato purée and stock, cover the pot and bring to a gentle boil, then add the tortellini and cook until tender, 2 to 3 minutes (1 minute longer if frozen).

## 3
Add the heavy cream, kale and basil, and cook, stirring, until warmed through and the kale and basil are just wilted, 2 minutes more. Remove from heat and add the lemon juice. Stir to incorporate, then taste and season with salt and pepper as needed.

## 4
Serve warm topped with plenty of grated Parmesan. Soup can be refrigerated for up to 5 days or frozen for up to 3 months.