---
title: "Crispy Gnocchi With Sausage and Broccoli"
categories: [Gnocchi, Sausage]
---

# Ingredients
- 18 oz package potato gnocchi
- 1 large head broccoli, 1 lb, florets cut into 1.5 - to 2-inch pieces, stems thinly sliced
- 0.25 cup extra-virgin olive oil
- 2 garlic cloves, minced
- Salt
- Crushed red pepper (optional)
- 1 lb hot or sweet Italian sausage, casings removed
- 0.25 cup grated Parmesan, plus more for serving
- Half of a lemon

# Instructions
## 1
- Heat the oven to 425 degrees
- On a sheet pan, toss together the gnocchi, broccoli, olive oil and garlic until well coated
- Season with salt and crushed red pepper, if using
- Spread into an even layer
- Pinch off pieces of the sausage that are roughly the size of the gnocchi and place them on top of the gnocchi and vegetables
- Roast until the sausage and broccoli are golden and crisp, 20 to 25 minutes

## 2
- Squeeze the lemon half over the top (about 1½ tablespoons juice) and sprinkle with the Parmesan
- Stir until the cheese has melted
- Serve topped with more Parmesan and crushed red pepper as you like