---
title: "Cauliflower Shawarma With Spicy Tahini"
description: |
  Veggie Shawarma
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
## For the Cauliflower
5tablespoons extra-virgin olive oil, plus more as needed
1¼teaspoons ground cumin
1¼teaspoons sweet paprika
¾teaspoon fine sea or table salt, plus more as needed
1teaspoon ground coriander
¼teaspoon ground turmeric
¼teaspoon freshly ground black pepper
Pinch of ground cayenne
1large head cauliflower (about 2½ pounds), trimmed and cut into bite-size florets
1large red onion, cut into ¼-inch wedges
Pita or flatbread, for serving
¼cup coarsely chopped parsley, plus more for serving
Chopped tomato, cucumber and olives, for serving

## For the Spicy Tahini Sauce
1tablespoon fresh lemon juice, plus more to taste
1 to 2teaspoons harissa paste or other hot sauce, or a large pinch of Urfa or Aleppo pepper, plus more to taste
1fat garlic clove, finely grated, passed through a press or minced
¼teaspoon fine sea or table salt
⅓cup tahini
⅓cup ice water, plus more as needed

# Instructions
## 1
Arrange racks in the upper and lower thirds of your oven. Heat oven to 425 degrees.

## 2
Prepare the cauliflower: In a large bowl, whisk together olive oil, cumin, paprika, salt, coriander, turmeric, black pepper and cayenne. Add cauliflower and onion, and toss until well coated. Spread mixture in a single layer on a rimmed baking sheet.

## 3
Roast vegetables on the top oven rack until they are golden brown, slightly crisp and tender, 30 to 40 minutes, stirring once or twice. If the vegetables look dry as they roast, drizzle with a little more olive oil.

## 4
As they cook, prepare the tahini sauce: Whisk together lemon juice, 1 teaspoon harissa, garlic and salt in a small bowl, and let sit for a minute or two to mellow the garlic. Whisk in tahini. Whisk in ice water, 1 tablespoon at a time, until the sauce is smooth and thin enough to drizzle. You may not need all of the water or you may need to add a little more: Tahini brands vary a lot. Taste and adjust seasoning, adding more harissa, lemon juice and salt if you like. The sauce should taste zippy and creamy.

## 5
Warm the pitas or flatbread by placing them directly on the bottom oven rack during the last 5 minutes as the vegetables roast. (Or you can warm the bread on another baking pan if that’s easier for you.)

## 6
Scatter parsley on top of the roasted vegetables and serve with warm pitas, tahini sauce, chopped tomato, cucumber and olives.