---
title: "Thai Chicken Meatball Soup"
description: |
  One pot soup
author: Michael Ellsworth
---

# Ingredients
1(4-inch) piece fresh ginger, peeled
6garlic cloves, peeled
1jalapeño
2pounds ground chicken
1large bunch cilantro, leaves and stems finely chopped, a few whole leaves reserved for serving
3tablespoons fish sauce
Kosher salt
2tablespoons vegetable or coconut oil, plus more as needed
2cups chicken broth
1(14-ounce) can full-fat coconut milk
½teaspoon granulated sugar
5ounces baby spinach
1tablespoon lime juice, plus lime wedges for serving
Steamed white or brown rice, for serving

# Instructions
## 1
Using the small holes of a box grater, or a Microplane, grate the ginger, garlic and jalapeño (or finely chop them by hand). Transfer half to a large bowl and set the rest aside. To the large bowl, add the chicken, finely chopped cilantro, 2 tablespoons fish sauce and 1 teaspoon salt. Use your hands or a fork to fully combine but do not overmix.
## 2
Use your hands or an ice cream scoop to form 2-inch meatballs (about 2 ounces each). In a large Dutch oven or pot, heat the oil over medium-high heat. Working in batches, add the meatballs in a single layer and cook, flipping halfway through, until golden brown on two sides, 5 to 8 minutes. Transfer to a plate and repeat, adding oil as needed.
## 3
Once all the meatballs are browned and out of the pot, if the oil is burned, wipe it out and add a bit more to the pot. Reduce the heat to medium, add the reserved ginger mixture and sauté until fragrant, about 1 minute. Add the chicken broth, coconut milk, sugar and the remaining 1 tablespoon fish sauce, and bring to a simmer. Add the meatballs and any juices from the plate, and simmer until the flavors come together and the meatballs are cooked through, 5 to 8 minutes.
## 4
Remove from heat, and stir in the spinach and lime juice. Divide rice among bowls, then top with meatballs, broth and cilantro. Serve with lime wedges.