---
title: "Tofu With Spicy Soy Dressing"
author:
  - name: "New York Times"
    href: https://cooking.nytimes.com/recipes/1022562-silken-tofu-with-spicy-soy-dressing
categories: [Tofu, Favourites]
---

# Ingredients
## For the Spicy Soy Dressing
- 0.25 cup soy sauce
- 1 tbsp rice vinegar
- 1 tbsp sesame oil
- 1 tbsp chile oil
- 1 tbsp toasted white sesame seeds
- 2 tsp granulated sugar
- 1 scallion, green and white parts, finely sliced

## For the Tofu
- 2 x 400g blocks firm/extra firm tofu, cold
- 1 scallion, green and white parts, thinly sliced
- Handful of cilantro leaves

# Instructions
## 1 - Make the dressing
- Combine in a small bowl:
  - Soy sauce
  - Rice vinegar
  - Sesame oil
  - Chile oil
  - Sesame seeds
  - Sugar
  - Green onions
- Whisk until the sugar has dissolved

## 2
- Carefully drain the liquid from the package of tofu, and gently tip the block onto a kitchen towel
- Try to keep the block in one piece, if possible, but don’t worry if it falls apart; it will still taste great
- Pat with another clean kitchen towel, removing as much liquid as possible
- Transfer the blocks to one large plate or two smaller plates — leave whole or cut into 1-inch blocks — and spoon the soy dressing over the top until the tofu is completely covered
- Top with scallions and cilantro leaves, and eat on its own or with rice or noodles on the side