---
title: "Pasta Salad"
description: |
  Pasta Salad
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients

## For the Dressing
3tablespoons red wine vinegar, plus more to taste
1garlic clove, finely grated or minced
1teaspoon dried oregano
Salt and freshly ground black pepper
⅓cup extra-virgin olive oil, plus more for drizzling

## For the Pasta
1pound short-cut pasta, such as farfalle
1pint cherry or grape tomatoes, halved
8ounces mozzarella, cubed (or use small mozzarella balls)
4ounces sliced salami, cut into ¼-inch ribbons
½cup thinly sliced cucumber
1cup coarsely chopped fresh parsley and basil leaves

# Instructions
## 1
Make the dressing: Combine vinegar, garlic, oregano and a big pinch each salt and pepper in a large bowl. Whisk in oil; taste and add more salt, pepper or vinegar as needed. Set aside.

## 2
Prepare the pasta: Bring a large pot of heavily salted water to a boil. Cook the pasta according to the package directions until the pasta is al dente. Drain well, transfer to the large bowl, and toss with the dressing while still warm.

## 3
Add tomatoes, mozzarella, salami, olives, cucumber and onion to the bowl and toss well; fold in herbs. Taste and season with more salt, pepper and vinegar, if you like.

## 4
Drizzle with olive oil and top with cracked black pepper just before serving.