---
title: "Buffalo Chickpea Wraps"
description: |
  Buffalo Chickpea Wraps
author: Michael Ellsworth
date: 2025-02-24
---

# Ingredients
1, 15 oz can chickpeas, drained and rinsed
2 cups of cauliflower florets (about 1 small head of cauliflower), cut into 1 inch pieces
1 1/2 tsp smoked paprika
1/2 tsp ground coriander
1/2 tsp dry thyme
1 1/2 tsp garlic powder
2 tbsp avocado oil
Salt to taste

## Sweet and Spicy Buffalo Sauce

3 tbsp buffalo sauce
2 tbsp tahini
2 tbsp plain unsweetened dairy-free yogurt
Juice of half a lemon
2 tsp maple syrup
Assemble

## Assemble
3 Burrito Sized Tortillas
Spinach
Shredded Carrots
Optional dipping sauce

# Instructions
## 1
Preheat the oven to 425F. Place your chickpeas on a clean kitchen towel and pat dry to remove excess moisture. Place the chickpeas and cauliflower on a large baking tray and in a small bowl whisk together the spice blend.

## 2
Sprinkle the spice blend, oil and a generous pinch of salt evenly over the chickpeas and cauliflower, then toss everything together until well coated. For even roasting, make sure to place the cauliflower florets cut side down on the baking tray and spread everything out evenly into a single layer.

## 3 
Place the baking tray on the middle rack of the oven and roast for 30 minutes, flipping the chickpeas and cauliflower half way through.

## 4
Meanwhile, prepare your sauce. Combine the buffalo sauce, yogurt, tahini, lemon and maple syrup together in a small bowl and whisk until smooth.

## 5
Place the roasted chickpeas and cauliflower in a mixing bowl then pour the buffalo sauce overtop and mix to coat.

## 6
Now assemble your wrap. Warm up your tortilla to make it pliable, then lay it on a flat surface. Top with greens and carrots then spoon on the cauliflower and chickpea mixture. Tuck and roll the burrito tight and place in a pan over medium low heat seam side down for 2-3 minutes, flip and cook another 2-3 minutes until both sides are golden then serve.
