---
title: "Shrimp Scampi With Orzo"
description: |
  Shrimp Scampi With Orzo
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
1pound large shrimp, peeled and deveined
3tablespoons extra-virgin olive oil
1tablespoon lemon zest, plus 1 tablespoon juice (from 1 lemon)
½teaspoon red-pepper flakes
Kosher salt (such as Diamond Crystal) and black pepper
4garlic cloves, minced
2tablespoons unsalted butter
1cup orzo
⅓cup dry white wine
2cups boiling water, seafood stock or chicken stock
3tablespoons finely chopped parsley

# Instructions
## 1
In a medium bowl, stir together shrimp, 1 tablespoon olive oil, lemon zest, red-pepper flakes, ½ teaspoon salt, ¼ teaspoon pepper and half of the garlic. Set aside to marinate. (This step can be done up to 1 hour in advance.)

## 2
Add butter, remaining olive oil and remaining garlic to a medium skillet set over medium heat. When the butter starts to bubble, add the orzo and ½ teaspoon salt and cook, stirring often, until the orzo is toasted, about 2 minutes, adjusting the heat as necessary to prevent the garlic from burning. Carefully add the wine — it will bubble — and stir until absorbed, about 1 minute. Stir in water, reduce heat to low, cover, and cook until orzo is al dente, about 12 minutes.

## 3
Add the shrimp in a snug, even layer on top of the orzo, cover, and cook until all the shrimp is pink and cooked through, 2 to 4 minutes. Remove from heat and let sit, covered, 2 minutes.

## 4
Sprinkle with parsley and lemon juice, season with salt and pepper, and serve immediately.