---
title: "Crispy Gnocchi With Sausage and Broccoli"
description: |
  Crispy gnocchi with sausage
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
1(12- to 18-ounce) package shelf-stable potato gnocchi
1large head broccoli (about 1 pound), florets cut into 1½- to 2-inch pieces, stems thinly sliced
¼ cup extra-virgin olive oil
2garlic cloves, finely grated
Salt
Crushed red pepper (optional)
1pound hot or sweet Italian sausage, casings removed
¼cup grated Parmesan, plus more for serving
½ lemon

# Instructions
## 1
Heat the oven to 425 degrees. On a sheet pan, toss together the gnocchi, broccoli, olive oil and garlic until well coated. Season with salt and crushed red pepper, if using. Spread into an even layer. Pinch off pieces of the sausage that are roughly the size of the gnocchi and place them on top of the gnocchi and vegetables. Roast until the sausage and broccoli are golden and crisp, 20 to 25 minutes.
## 2
Squeeze the lemon half over the top (about 1½ tablespoons juice) and sprinkle with the Parmesan. Stir until the cheese has melted. Serve topped with more Parmesan and crushed red pepper as you like.
