---
title: "Chimichurri Meatballs"
author:
  - name: "New York Times"
    href: https://cooking.nytimes.com/recipes/1025007-chimichurri-meatballs
categories: Beef
---

# Ingredients
## For the Chimichurri Sauce
- 1 packed cup parsley leaves and tender stems
- 0.5 packed cup fresh oregano leaves
- 3 garlic cloves
- Salt
- 0.5 cup extra-virgin olive oil
- 2 tbsps red wine vinegar
- 0.5 tsp crushed red pepper, plus more as needed

## For the Meatballs
- 1 cup panko bread crumbs
- 1 large egg
- Kosher salt
- 1 pound ground beef (preferably 15 percent fat)
- 1 tbsp EVOO

# Instructions
## 1
- To make the chimichurri, on your cutting board or in a food processor, combine the parsley, oregano, garlic and a big pinch of salt
- Chop or pulse until a coarse, juicy paste forms, then transfer to a medium bowl
- Add the oil, vinegar, crushed red pepper and 1 tbsp water; mix well
- Season to taste with salt and more crushed red pepper to taste
- Sauce can be refrigerated for up to 3 days

## 2
- In a large bowl, stir the panko, egg, 1 tsp kosher salt (or 0.5 tsp fine sea salt) with 0.25 cup water and 0.25 cup chimichurri until the panko is wet and softened
- Add the beef and use your hands to mix until combined

## 3
- Roll the mixture into 12 meatballs (3 tbsp/2 ounces each) and chill for 5 to 10 minutes to firm slightly

## 4
- Heat the oil in a large, nonstick skillet over medium
- Add the meatballs and cook, turning occasionally, until browned and medium-rare, or to desired doneness, 7 to 10 minutes
- Serve with remaining chimichurri spooned over top and alongside