---
title: "Chimichurri Chicken"
categories: Chicken
---

# Ingredients
## For the Chimichurri Sauce
- 3 garlic cloves, peeled
- 1.5 tsp kosher salt
- 1 cup parsley leaves and stems
- 0.5 cup fresh oregano leaves
- 0.5 tsp red-pepper flakes
- 0.5 tsp black pepper
- 3 tbsp red-wine vinegar
- 0.5 cup extra-virgin olive oil

## For the Chicken
- 1.5 to 2 lb boneless, skinless chicken thighs or breasts
- 1 tbsp olive oil

# Instructions
## 1
- Make the sauce: On a cutting board, smash and coarsely chop the garlic with 0.5 tsp salt
- Mash the mixture using the side of your knife until a coarse paste forms
- Move the paste to the side of the cutting board, then chop the parsley and oregano together with the remaining 1 tsp salt
- Combine the garlic paste and the chopped herbs and chop and mash until the herbs are bruised and fragrant

## 2
- Transfer to a medium bowl
- Add the red-pepper flakes, black pepper, vinegar and extra-virgin olive oil; stir to combine
- You should have about 0.75 cup chimichurri. It can be prepared in advance and refrigerated in an airtight container up to 2 days

## 3
- Make the chicken: Pat the chicken dry. If thickness varies greatly, pound to an even thickness, about 0.5 inch
- Rub half the chimichurri all over the chicken and let sit for at least 10 minutes
- You could also refrigerate overnight; just let it come to room temperature before cooking

## 4
- Heat the olive oil in a large skillet over medium-high
- Wipe off excess marinade from the chicken and cook until juices run clear, about 5 minutes per side for thighs and 4 minutes per side for breasts
- For grilling and oven instructions, see Tips below

## 5
- Serve with remaining chimichurri spooned over top

## Tips
- Oven instructions: Heat oven to 425 degrees. Oil a foil-lined baking sheet, then add the chicken and roast until cooked through and juices run clear, 15 to 20 minutes
- Grilling instructions: Heat a grill to medium-high. Oil the grates. Wipe off excess marinade from the chicken, then grill over direct heat until cooked through and juices run clear, about 5 minutes per side for thighs and about 3 minutes per side for breasts