---
title: "Dijonnaise Grilled Chicken Breasts"
description: |
  Grilled chicken
author: Michael Ellsworth
date: 2025-02-21
---

# Ingredients
½cup mayonnaise
½cup Dijon mustard
2garlic cloves, finely grated
Salt and black pepper
1teaspoon thyme leaves or dried thyme
1½ to 2 pounds boneless, skinless chicken breasts or thighs, patted dry

# Instructions
## 1
Heat a grill to medium-high. (You can also cook the chicken on the stovetop over medium-high heat, following the same timing.) Meanwhile, in a medium bowl, stir together the mayonnaise, mustard and garlic, and season to taste with salt and pepper. Transfer half to a small bowl and refrigerate until serving.

## 2
To the medium bowl with the reserved Dijonnaise, stir in the thyme leaves. Season the chicken all over with salt and pepper, then transfer to the medium bowl and toss to coat. Let sit at least 15 minutes, or refrigerate up to overnight. (Let it come to room temperature before cooking.)

## 3
Clean the grill grates. (No need to grease; the mayonnaise keeps the chicken from sticking.) Scrape excess marinade off the chicken, then grill over direct heat until the chicken unsticks from the grates and is deep golden and cooked through, 4 to 6 minutes per side. If using a gas grill, cover grill between flips. Discard the chicken marinade. Serve with the small bowl of reserved Dijonnaise alongside.