---
title: "Baked Chicken Thighs"
author:
  - name: "New York Times"
    url: https://cooking.nytimes.com/recipes/1024625-baked-chicken-thighs
categories: Chicken
---
# Notes
- Marinate time is 30 minutes to 12 hours
- Chicken should be 165F to 175F when cooked

# Ingredients
- 1/3 cup olive oil
- 2 large cloves garlic (1 tbsp)
- 1 tbsp Dijon mustard
- 2 tsp dried thyme, rosemary or oregano (or 1 tbsp fresh), or 2 tsp Italian seasoning
  - Thyme works best here
- 1.5 tsp salt
- 1 tsp black pepper
- 1 lemon
- 6 to 8 chicken thighs (1.5 kg)
- Fresh parsley, for serving (optional)

# Instructions
## 0.5
- Mince garlic cloves
- Pat chicken dry
- Zest lemon
- Chop parsley (if serving)

## 1
- In a large bowl, combine olive oil, garlic, mustard, thyme, salt and pepper, lemon zest and whisk until combined

## 2
- Add chicken thighs to the bowl, fully coating in the marinade
- Cover and marinate for 30 minutes at room temperature, or up to 12 hours in the fridge

## 3
- Preheat oven to 425 degrees
- Lift the chicken thighs from the marinade, letting any excess drip into the bowl
- Place the thighs on a sheet pan and let them sit at room temperature while the oven heats
- Bake until fully cooked and lightly browned, 25 to 30 minutes

## 4
- Cut the lemon in half and squeeze over the chicken
- Sprinkle with salt, parsley and serve